name: Deploy Juice Shop to AKS
on:
  push:
    branches:
      - main

jobs:
  fcs-iac-scan:
    name: Run FCS IaC scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run FCS IaC Scan
        id: fcs_scan
        uses: crowdstrike/fcs-action@v2.0.2
        with:
          # Either supply the client id directly or reference a repo variable (recommended):
          falcon_client_id: ${{ var.FALCON_CLIENT_ID }}   # or ${{ vars.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'                              # set the region for your tenant
          scan_type: 'iac'                                   # iac or image
          path: 'git::https://github.com/mile9299/IAC_Examples.git'                           # path to IaC (file/dir/git::repo)
          report_formats: 'json'                            # request SARIF for GH Code Scanning
          output_path: "./fcs-results/fcs-iac.json"                       # must be a directory for IaC scan
          fail_on: 'critical=1,high=1'                       # fail job if criteria met (customize)
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
  fcs-image-scan:
    name: Scan Container Image
    uses: crowdstrike/fcs-action@v2.0.2
    with:
      falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
      falcon_client_secret: ${{ secrets.FALCON_CLIENT_SECRET }
      falcon_region: 'us-1'
      scan_type: image
      image: scorpas/spooky
      output_path: './fcs-results/'
      report_formats: json
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
      K8S_NAMESPACE: apps

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # <-- add this
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Show kubectl cluster info
        run: kubectl cluster-info

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -n $K8S_NAMESPACE -f k8s/deployment.yaml
          kubectl apply -n $K8S_NAMESPACE -f k8s/service.yaml

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/juice-shop -n $K8S_NAMESPACE --timeout=120s
