name: Deploy Juice Shop to AKS

on:
  push:
    branches:
      - main

jobs:
  fcs-scan-iac:
    name: FCS Falcon Cloud Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Falcon Cloud Security IaC Scan
        id: fcs_scan
        uses: crowdstrike/fcs-action@v2.0.2
        with:
          falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'
          scan_type: 'iac'
          path: 'git::https://github.com/mile9299/IAC_Examples.git'
          report_formats: 'json'
          upload_results: 'true'
          output_path: './fcs-results/fcs-iac.json'
          fail_on: 'critical=1,high=1'
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

  fcs-scan-image:
    name: Run Falcon Cloud Security Image Scan
    runs-on: ubuntu-latest
    needs: fcs-scan-iac
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan Container Image
        id: fcs_image_scan
        uses: crowdstrike/fcs-action@v2.0.2
        with:
          falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'
          scan_type: 'image'
          image: 'scorpas/spooky'
          report_formats: 'json'
          upload_results: 'true'
          output_path: './image-scan-results/image-scan-results.json'
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

  deploy-juice-shop:
    name: Deploy Juice Shop App to AKS
    runs-on: ubuntu-latest
    needs: fcs-scan-image
    env:
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
      K8S_NAMESPACE: apps
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Show kubectl cluster info
        run: kubectl cluster-info

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -n $K8S_NAMESPACE -f k8s/deployment.yaml
          kubectl apply -n $K8S_NAMESPACE -f k8s/service.yaml

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/juice-shop -n $K8S_NAMESPACE --timeout=120s
